version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: bibliotekapi/Dockerfile
    container_name: library_api
    command: uvicorn bibliotekapi.src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_NAME: library_db
    volumes:
      - ./bibliotekapi/src:/app/src
    depends_on:
      - db
