services:
  app:
    build:
      context: bibliotekapi/
    ports:
      - "8000:8000"
    volumes:
      - ./bibliotekapi/src:/src
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=pass
    depends_on:
      - db
    networks:
      - backend
    container_name: library-app

  
  db:
    image: postgres:17.0-alpine3.20
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    networks:
      - backend
    container_name: library-db
    

networks:
  backend: